### ISSUE TITLE
Get jtdsp16 module - access denied by the command "git clone --recursive https://github.com/jotego/jtcps1.git"

### ISSUE THREAD

**Issue by wwark** [jotego/jtdsp16#1]
When we try to get jtcps1.git with submodule we have a denied to get "git@github.com:jotego/jtdsp16.git"
The configuration of this module seems different than other modules (https://github.com/jotego/jtframe for example).

> git clone --recursive https://github.com/jotego/jtcps1.git
Cloning into 'jtcps1'...
remote: Enumerating objects: 13917, done.
remote: Counting objects: 100% (7362/7362), done.
remote: Compressing objects: 100% (1814/1814), done.
remote: Total 13917 (delta 5466), reused 7044 (delta 5161), pack-reused 6555
Receiving objects: 100% (13917/13917), 66.88 MiB | 2.89 MiB/s, done.
Resolving deltas: 100% (10894/10894), done.
Submodule 'modules/fx68k' (https://github.com/ijor/fx68k) registered for path 'modules/fx68k'
Submodule 'modules/jt51' (https://github.com/jotego/jt51) registered for path 'modules/jt51'
Submodule 'modules/jt6295' (https://github.com/jotego/jt6295) registered for path 'modules/jt6295'
Submodule 'modules/jtdsp16' (git@github.com:jotego/jtdsp16.git) registered for path 'modules/jtdsp16'
Submodule 'modules/jteeprom' (https://github.com/jotego/jteeprom.git) registered for path 'modules/jteeprom'
Submodule 'modules/jtframe' (https://github.com/jotego/jtframe) registered for path 'modules/jtframe'
Cloning into '/home/***/Dev/MisterDev/jotego/jtcps1/modules/fx68k'...
remote: Enumerating objects: 33, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 33 (delta 0), reused 1 (delta 0), pack-reused 30        
Cloning into '/home/***/Dev/MisterDev/jotego/jtcps1/modules/jt51'...
remote: Enumerating objects: 1182, done.        
remote: Counting objects: 100% (200/200), done.        
remote: Compressing objects: 100% (141/141), done.        
remote: Total 1182 (delta 110), reused 137 (delta 56), pack-reused 982        
Receiving objects: 100% (1182/1182), 2.22 MiB | 2.77 MiB/s, done.
Resolving deltas: 100% (719/719), done.
Cloning into '/home/***/Dev/MisterDev/jotego/jtcps1/modules/jt6295'...
remote: Enumerating objects: 276, done.        
remote: Counting objects: 100% (276/276), done.        
remote: Compressing objects: 100% (201/201), done.        
remote: Total 276 (delta 180), reused 163 (delta 70), pack-reused 0        
Receiving objects: 100% (276/276), 343.66 KiB | 1.81 MiB/s, done.
Resolving deltas: 100% (180/180), done.
Cloning into '/home/****/Dev/MisterDev/jotego/jtcps1/modules/jtdsp16'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:jotego/jtdsp16.git' into submodule path '/home/***/Dev/MisterDev/jotego/jtcps1/modules/jtdsp16' failed
Failed to clone 'modules/jtdsp16'. Retry scheduled

Thanks,

**Comment by paulb-nl** [comment]
You probably don't have your SSH keypair setup properly which is needed with git@github.com. Check here: https://gist.github.com/grawity/4392747

**Comment by wwark** [comment]
Thanks for the return. I can close this ticket.

Previously we have this configuration for submodules

Submodule 'modules/fx68k' (https://github.com/ijor/fx68k) registered for path 'modules/fx68k'
Submodule 'modules/jt51' (https://github.com/jotego/jt51) registered for path 'modules/jt51'
Submodule 'modules/jt6295' (https://github.com/jotego/jt6295) registered for path 'modules/jt6295'
**Submodule 'modules/jtdsp16' (git@github.com:jotego/jtdsp16.git) registered for path 'modules/jtdsp16'**
Submodule 'modules/jteeprom' (https://github.com/jotego/jteeprom.git) registered for path 'modules/jteeprom'
Submodule 'modules/jtframe' (https://github.com/jotego/jtframe) registered for path 'modules/jtframe'

Now the jtdsp16 is ok.

Submodule 'modules/fx68k' (https://github.com/ijor/fx68k) registered for path 'modules/fx68k'
Submodule 'modules/jt51' (https://github.com/jotego/jt51) registered for path 'modules/jt51'
Submodule 'modules/jt6295' (https://github.com/jotego/jt6295) registered for path 'modules/jt6295'
**Submodule 'modules/jtdsp16' (https://github.com/jotego/jtdsp16.git) registered for path 'modules/jtdsp16'**
Submodule 'modules/jteeprom' (https://github.com/jotego/jteeprom.git) registered for path 'modules/jteeprom'
Submodule 'modules/jtframe' (https://github.com/jotego/jtframe) registered for path 'modules/jtframe'

So the case is fixed.
